# Navigate panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resize pane
bind-key -r C-k resize-pane -U 1
bind-key -r C-j resize-pane -D 1
bind-key -r C-h resize-pane -L 1
bind-key -r C-l resize-pane -R 1

# vi bindings
set-window-option -g mode-keys vi

unbind r
bind r source-file ~/.dotfiles/tmux/.config/tmux/tmux.conf \; display-message 'tmux.conf reloaded...'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Enable restores
set -g @continuum-restore 'on'

# TPM initialization
run '~/.dotfiles/tmux/.config/tmux/plugins/tpm/tpm'
